#!/usr/bin/env node
// The ONLY entry point to the contract codegen chain in this repository, and
// the whole of `pnpm contracts:emit`.
//
//   packages/contracts (Zod)  →  z.toJSONSchema()  →  one JSON Schema document
//                             →  datamodel-codegen →  committed pydantic models
//
// Both halves live here rather than one of them living in `packages/contracts`,
// and that is a measured constraint rather than a preference:
//
//   - The Zod→JSON Schema half is `src/json-schema.ts`, so it is type-checked,
//     linted and covered like the rest of the package. It cannot do the file
//     write, because `packages/contracts` may import nothing but `zod` — the
//     `contractsBoundary` ESLint rule rejects `node:fs` in `src/**`, on purpose:
//     this package ends up in a browser bundle.
//   - A companion script under `packages/contracts/scripts/` cannot bridge that
//     gap either. It would have to import `../src/json-schema.js`, and MEASURED
//     on node 24.19.0, Node's native type stripping does NOT rewrite a `.js`
//     specifier to the `.ts` file on disk (`ERR_MODULE_NOT_FOUND`), while
//     importing `../dist/…` instead makes `pnpm typecheck` depend on a build
//     that turbo's `typecheck` task does not schedule for the package itself.
//
// So this file imports the BUILT `dist/json-schema.js` — the same shape as
// `apps/api`'s `openapi:emit`, which runs `dist/scripts/emit-openapi.js` — and
// builds it first so that a fresh clone needs nothing but `pnpm install`.
//
// The intermediate JSON Schema document is deliberately NOT committed. There is
// exactly one generated artefact under review, the pydantic models, and a second
// committed file derived from the same source is a second thing to keep in sync
// and a second `.prettierignore` entry. It is written to a temporary directory
// and its path is printed, so it can still be inspected after a run.
import { spawnSync } from 'node:child_process';
import { mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { pathToFileURL, fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const workersRoot = path.join(repoRoot, 'apps/workers');
const emitted = path.join(
  workersRoot,
  'packages/metrika_core/src/metrika_core/contracts/__init__.py',
);

/**
 * Replaces datamodel-codegen's own header, which names the INPUT FILENAME —
 * a temporary path here, and therefore the one thing in the output that would
 * not be reproducible. `--disable-timestamp` removes the other one.
 *
 * It is also the only place documentation can live in a file that is byte-diffed
 * in CI: nothing may be added to the output by hand, so anything a reader needs
 * to know has to be an input to the generator. Keep every line under 100
 * characters — `--formatters ruff-check` runs the repository's own `ruff` over
 * the result, and `E501` applies to comments.
 */
const HEADER = `# GENERATED BY \`pnpm contracts:emit\`. DO NOT EDIT.
#
# Source of truth: packages/contracts (Zod) → z.toJSONSchema() → datamodel-codegen.
# Edit the Zod schema and re-run \`pnpm contracts:emit\`; CI diffs this file and
# fails if it is stale. See docs/CONTRACTS_AND_API.md §5 and ADR-0027.
#
# WHAT DID NOT SURVIVE THE CROSSING, because nothing here can show you:
#
#   BRANDING. \`QuoteId\` and \`OrderId\` are the same constrained \`str\` in Python
#   and are freely interchangeable; on the TypeScript side they are distinct
#   types and a mix-up is a compile error. ADR-0018's identity does not cross
#   this boundary and cannot be made to. What DOES cross is the validation:
#   the pattern below is the same one Zod enforces.
#
#   REGEX FLAGS. z.toJSONSchema() emits a pattern's source and drops its flags
#   silently, which is why the UUID pattern spells its case classes out.
#
# And one thing that crosses but means something DIFFERENT on this side:
#
#   \`\\d\` is ASCII-only in JavaScript and matches any Unicode decimal digit in
#   Python, so a pattern containing one would make this file strictly more
#   permissive than the schema that defines it — "3\\u0665\\u0660" would parse as
#   350. No pattern here contains one; tests/test_generated_contracts.py is
#   where that is asserted, on this side, where it is observable.`;

function run(command, args, options = {}) {
  const result = spawnSync(command, args, { stdio: 'inherit', ...options });
  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

// `tsc -b`, so this is a no-op on an up-to-date tree and the reason
// `dist/json-schema.js` below always exists.
run('pnpm', ['--filter', '@metrika/contracts', 'run', 'build'], { cwd: repoRoot });

const { contractsJsonSchemaDocument } = await import(
  pathToFileURL(path.join(repoRoot, 'packages/contracts/dist/json-schema.js')).href
);

const scratch = mkdtempSync(path.join(tmpdir(), 'metrika-contracts-'));
const document = path.join(scratch, 'contracts.schema.json');
writeFileSync(document, `${JSON.stringify(contractsJsonSchemaDocument(), null, 2)}\n`, 'utf8');
process.stdout.write(`contracts:emit — JSON Schema written to ${document}\n`);

// Every flag is load-bearing; ADR-0027 obligation 4 has the measurements.
//
//   --disable-timestamp    the default header carries a generation timestamp,
//                          so two runs seconds apart differ and the CI diff gate
//                          is red on every run that is not in the same second.
//   --use-annotated        the default emits `constr(pattern=…)` — a function
//                          call in annotation position, which `mypy --strict`
//                          rejects outright (`valid-type`, exit 1) in the file
//                          it has just generated.
//   --formatters
//     ruff-format
//     ruff-check           datamodel-codegen otherwise formats with `black` and
//                          `isort` (which it installs), whose output `ruff
//                          format --check` rejects — `pnpm format:check` would
//                          be red forever on a freshly generated file. The flag
//                          takes SPACE-SEPARATED values; repeating the flag
//                          keeps only the last and silently applies one
//                          formatter instead of two.
//
// The consequence, and it is not obvious from either side: the committed bytes
// are a function of the pinned `ruff` and of `[tool.ruff]` in
// apps/workers/pyproject.toml, not of the schema alone. A `line-length` change
// there reflows this output. Regenerate and commit in the SAME commit as any
// such change (ADR-0027 obligation 6), or an unrelated pull request goes red in
// a file it never touched.
run(
  'uv',
  [
    'run',
    '--locked',
    '--all-packages',
    'datamodel-codegen',
    '--input',
    document,
    '--input-file-type',
    'jsonschema',
    '--output',
    emitted,
    '--output-model-type',
    'pydantic_v2.BaseModel',
    '--target-python-version',
    '3.12',
    '--disable-timestamp',
    '--use-annotated',
    '--custom-file-header',
    HEADER,
    '--formatters',
    'ruff-format',
    'ruff-check',
  ],
  { cwd: workersRoot },
);

process.stdout.write(`contracts:emit — pydantic models written to ${emitted}\n`);
