#!/usr/bin/env node
// The ONLY entry point to the contract codegen chain in this repository, and
// the whole of `pnpm contracts:emit`.
//
//   packages/contracts (Zod)  →  z.toJSONSchema()  →  one JSON Schema document
//                             →  datamodel-codegen →  committed pydantic models
//
// Both halves live here rather than one of them living in `packages/contracts`,
// and that is a measured constraint rather than a preference:
//
//   - The Zod→JSON Schema half is `src/json-schema.ts`, so it is type-checked,
//     linted and covered like the rest of the package. It cannot do the file
//     write, because `packages/contracts` may import nothing but `zod` — the
//     `contractsBoundary` ESLint rule rejects `node:fs` in `src/**`, on purpose:
//     this package ends up in a browser bundle.
//   - A companion script under `packages/contracts/scripts/` cannot bridge that
//     gap either. It would have to import `../src/json-schema.js`, and MEASURED
//     on node 24.19.0, Node's native type stripping does NOT rewrite a `.js`
//     specifier to the `.ts` file on disk (`ERR_MODULE_NOT_FOUND`), while
//     importing `../dist/…` instead makes `pnpm typecheck` depend on a build
//     that turbo's `typecheck` task does not schedule for the package itself.
//
// So this file imports the BUILT `dist/json-schema.js` — the same shape as
// `apps/api`'s `openapi:emit`, which runs `dist/scripts/emit-openapi.js` — and
// builds it first so that a fresh clone needs nothing but `pnpm install`.
//
// The intermediate JSON Schema document is deliberately NOT committed. There is
// exactly one generated artefact under review, the pydantic models, and a second
// committed file derived from the same source is a second thing to keep in sync
// and a second `.prettierignore` entry. It is written to a temporary directory
// and its path is printed, so it can still be inspected after a run.
import { spawnSync } from 'node:child_process';
import { existsSync, mkdtempSync, writeFileSync } from 'node:fs';
import { tmpdir } from 'node:os';
import path from 'node:path';
import { pathToFileURL, fileURLToPath } from 'node:url';

const repoRoot = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const workersRoot = path.join(repoRoot, 'apps/workers');
const emitted = path.join(
  workersRoot,
  'packages/metrika_core/src/metrika_core/contracts/__init__.py',
);

/**
 * Replaces datamodel-codegen's own header, which names the INPUT FILENAME —
 * a temporary path here, and therefore the one thing in the output that would
 * not be reproducible. `--disable-timestamp` removes the other one.
 *
 * It is also the only place documentation can live in a file that is byte-diffed
 * in CI: nothing may be added to the output by hand, so anything a reader needs
 * to know has to be an input to the generator. Keep every line under 100
 * characters — `--formatters ruff-check` runs the repository's own `ruff` over
 * the result, and `E501` applies to comments.
 */
const HEADER = `# GENERATED BY \`pnpm contracts:emit\`. DO NOT EDIT.
#
# Source of truth: packages/contracts (Zod) → z.toJSONSchema() → datamodel-codegen.
# Edit the Zod schema and re-run \`pnpm contracts:emit\`; CI diffs this file and
# fails if it is stale. See docs/CONTRACTS_AND_API.md §5 and ADR-0027.
#
# WHAT DID NOT SURVIVE THE CROSSING, because nothing here can show you:
#
#   BRANDING. \`QuoteId\` and \`OrderId\` are the same constrained \`str\` in Python
#   and are freely interchangeable; on the TypeScript side they are distinct
#   types and a mix-up is a compile error. ADR-0018's identity does not cross
#   this boundary and cannot be made to. What DOES cross is the validation:
#   the pattern below is the same one Zod enforces.
#
#   REGEX FLAGS. z.toJSONSchema() emits a pattern's source and drops its flags
#   silently, which is why the UUID pattern spells its case classes out.
#
# And one that crosses INTO A DIFFERENT RULE, in the safe direction:
#
#   UNKNOWN KEYS. Zod's default object mode STRIPS an unknown key and accepts
#   the object; \`additionalProperties: false\` is emitted anyway, so pydantic
#   FORBIDS it. A payload TypeScript accepts can therefore be rejected here.
#   Listed because this header claims to enumerate the divergences, not because
#   it is a hazard: tests/test_generated_contracts.py pins the strict side.
#
# And two things that cross ONLY because they were made to. Removing either
# reopens a hole that is invisible from the TypeScript side:
#
#   FINITENESS. JSON Schema cannot say "finite", and a bare pydantic float
#   ACCEPTS NaN, +inf and -inf where z.number() rejects all three. The units
#   therefore carry \`minimum\`/\`maximum\` at ±Number.MAX_VALUE, which IS the set
#   of finite doubles — ±inf fall outside it and NaN fails every comparison.
#   The bounds read like a no-op on the Zod side. They are not one here.
#
#   THE INPUT TYPE. pydantic's lax mode reads "12.5" and True as floats and
#   "2" and True as ints; Zod rejects all four. \`--strict-types\` is what closes
#   that, and an int is still accepted for a float, because Zod accepts one.
#
# And one thing that crosses but means something DIFFERENT on this side:
#
#   \`\\d\` is ASCII-only in JavaScript and matches any Unicode decimal digit in
#   Python, so a pattern containing one would make this file strictly more
#   permissive than the schema that defines it — "3\\u0665\\u0660" would parse as
#   350. No pattern here contains one; tests/test_generated_contracts.py is
#   where that is asserted, on this side, where it is observable.`;

function run(command, args, options = {}) {
  const result = spawnSync(command, args, { stdio: 'inherit', ...options });
  if (result.status !== 0) {
    process.exit(result.status ?? 1);
  }
}

// `tsc -b`, so this is a no-op on an up-to-date tree and the reason
// `dist/json-schema.js` below always exists.
//
// THROUGH TURBO, NOT `pnpm --filter`, and this repository already documents
// why: `pnpm --filter <no-match> run <script>` exits **0**, so a package rename
// would silently skip the build here — and with a `dist/` left over from an
// earlier run, the next line would then emit from STALE CODE at exit 0 and the
// CI diff gate would pass on models nobody generated. `turbo run` exits 1 on a
// filter that matches nothing and errors outright on a task no package declares.
// Same reasoning as `format:check` in turbo.json.
const distEntry = path.join(repoRoot, 'packages/contracts/dist/json-schema.js');
run('pnpm', ['exec', 'turbo', 'run', 'build', '--filter=@metrika/contracts'], { cwd: repoRoot });

// Belt and braces, and cheap: turbo restores declared outputs on a cache hit, so
// a build reported successful with no artefact on disk is a turbo-configuration
// bug rather than a compile error, and it must not surface three lines later as
// an unresolved dynamic import.
if (!existsSync(distEntry)) {
  process.stderr.write(
    `contracts:emit — the build reported success but ${distEntry} does not exist.\n` +
      "Check `outputs` in packages/contracts' turbo.json before re-running.\n",
  );
  process.exit(1);
}

const { contractsJsonSchemaDocument } = await import(pathToFileURL(distEntry).href);

const scratch = mkdtempSync(path.join(tmpdir(), 'metrika-contracts-'));
const document = path.join(scratch, 'contracts.schema.json');
writeFileSync(document, `${JSON.stringify(contractsJsonSchemaDocument(), null, 2)}\n`, 'utf8');
process.stdout.write(`contracts:emit — JSON Schema written to ${document}\n`);

// Every flag is load-bearing; ADR-0027 obligation 4 has the measurements.
//
//   --disable-timestamp    the default header carries a generation timestamp,
//                          so two runs seconds apart differ and the CI diff gate
//                          is red on every run that is not in the same second.
//   --use-annotated        the default emits `constr(pattern=…)` — a function
//                          call in annotation position, which `mypy --strict`
//                          rejects outright (`valid-type`, exit 1) in the file
//                          it has just generated.
//   --strict-types …       pydantic's LAX mode reads "12.5" and True as floats
//                          and "2" and True as ints. Zod rejects all four, so
//                          without this the generated model is more permissive
//                          than the schema defining it — the same direction as
//                          the `\d` defect. MEASURED: `StrictFloat` still
//                          accepts an int, which is right, because `z.number()`
//                          does. It does NOT fix NaN/±inf; the `minimum`/
//                          `maximum` bounds in `units.ts` are what do that.
//   --formatters
//     ruff-format
//     ruff-check           datamodel-codegen otherwise formats with `black` and
//                          `isort` (which it installs), whose output `ruff
//                          format --check` rejects — `pnpm format:check` would
//                          be red forever on a freshly generated file. The flag
//                          takes SPACE-SEPARATED values; repeating the flag
//                          keeps only the last and silently applies one
//                          formatter instead of two.
//
// The consequence, and it is not obvious from either side: the committed bytes
// are a function of the pinned `ruff` and of `[tool.ruff]` in
// apps/workers/pyproject.toml, not of the schema alone. A `line-length` change
// there reflows this output. Regenerate and commit in the SAME commit as any
// such change (ADR-0027 obligation 6), or an unrelated pull request goes red in
// a file it never touched.
run(
  'uv',
  [
    'run',
    '--locked',
    '--all-packages',
    'datamodel-codegen',
    '--input',
    document,
    '--input-file-type',
    'jsonschema',
    '--output',
    emitted,
    '--output-model-type',
    'pydantic_v2.BaseModel',
    '--target-python-version',
    '3.12',
    '--disable-timestamp',
    '--use-annotated',
    '--strict-types',
    'str',
    'bytes',
    'int',
    'float',
    'bool',
    '--custom-file-header',
    HEADER,
    '--formatters',
    'ruff-format',
    'ruff-check',
  ],
  { cwd: workersRoot },
);

process.stdout.write(`contracts:emit — pydantic models written to ${emitted}\n`);
