# GENERATED BY `pnpm contracts:emit`. DO NOT EDIT.
#
# Source of truth: packages/contracts (Zod) → z.toJSONSchema() → datamodel-codegen.
# Edit the Zod schema and re-run `pnpm contracts:emit`; CI diffs this file and
# fails if it is stale. See docs/CONTRACTS_AND_API.md §5 and ADR-0027.
#
# WHAT DID NOT SURVIVE THE CROSSING, because nothing here can show you:
#
#   BRANDING. `QuoteId` and `OrderId` are the same constrained `str` in Python
#   and are freely interchangeable; on the TypeScript side they are distinct
#   types and a mix-up is a compile error. ADR-0018's identity does not cross
#   this boundary and cannot be made to. What DOES cross is the validation:
#   the pattern below is the same one Zod enforces.
#
#   REGEX FLAGS. z.toJSONSchema() emits a pattern's source and drops its flags
#   silently, which is why the UUID pattern spells its case classes out.
#
# And one that crosses INTO A DIFFERENT RULE, in the safe direction:
#
#   UNKNOWN KEYS. Zod's default object mode STRIPS an unknown key and accepts
#   the object; `additionalProperties: false` is emitted anyway, so pydantic
#   FORBIDS it. A payload TypeScript accepts can therefore be rejected here.
#   Listed because this header claims to enumerate the divergences, not because
#   it is a hazard: tests/test_generated_contracts.py pins the strict side.
#
# And two things that cross ONLY because they were made to. Removing either
# reopens a hole that is invisible from the TypeScript side:
#
#   FINITENESS. JSON Schema cannot say "finite", and a bare pydantic float
#   ACCEPTS NaN, +inf and -inf where z.number() rejects all three. The units
#   therefore carry `minimum`/`maximum` at ±Number.MAX_VALUE, which IS the set
#   of finite doubles — ±inf fall outside it and NaN fails every comparison.
#   The bounds read like a no-op on the Zod side. They are not one here.
#
#   THE INPUT TYPE. pydantic's lax mode reads "12.5" and True as floats and
#   "2" and True as ints; Zod rejects all four. `--strict-types` is what closes
#   that, and an int is still accepted for a float, because Zod accepts one.
#
# And one thing that crosses but means something DIFFERENT on this side:
#
#   `\d` is ASCII-only in JavaScript and matches any Unicode decimal digit in
#   Python, so a pattern containing one would make this file strictly more
#   permissive than the schema that defines it — "3\u0665\u0660" would parse as
#   350. No pattern here contains one; tests/test_generated_contracts.py is
#   where that is asserted, on this side, where it is observable.

from __future__ import annotations

from enum import StrEnum
from typing import Annotated

from pydantic import BaseModel, ConfigDict, Field, RootModel, StrictFloat, StrictInt, StrictStr


class MetrikaContracts(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )


class CubicMillimeters(RootModel[StrictFloat]):
    root: Annotated[StrictFloat, Field(ge=0.0, le=1.7976931348623157e308)]


class CurrencyCode(StrEnum):
    COP = "COP"
    USD = "USD"
    EUR = "EUR"
    MXN = "MXN"


class DomainErrorCode(StrEnum):
    VALIDATION_FAILED = "VALIDATION_FAILED"
    ROUTE_NOT_FOUND = "ROUTE_NOT_FOUND"
    UNAUTHENTICATED = "UNAUTHENTICATED"
    INSUFFICIENT_PERMISSIONS = "INSUFFICIENT_PERMISSIONS"
    MODEL_NOT_FOUND = "MODEL_NOT_FOUND"
    MODEL_NOT_READY = "MODEL_NOT_READY"
    MODEL_NOT_PRINTABLE = "MODEL_NOT_PRINTABLE"
    MODEL_TOO_COMPLEX = "MODEL_TOO_COMPLEX"
    UNSUPPORTED_FILE_FORMAT = "UNSUPPORTED_FILE_FORMAT"
    FILE_TOO_LARGE = "FILE_TOO_LARGE"
    CHECKSUM_MISMATCH = "CHECKSUM_MISMATCH"
    MALICIOUS_ARCHIVE = "MALICIOUS_ARCHIVE"
    UNITS_NOT_CONFIRMED = "UNITS_NOT_CONFIRMED"
    IMPLAUSIBLE_SCALE = "IMPLAUSIBLE_SCALE"
    GEOMETRY_ANALYSIS_FAILED = "GEOMETRY_ANALYSIS_FAILED"
    INVALID_PRINT_CONFIGURATION = "INVALID_PRINT_CONFIGURATION"
    DOES_NOT_FIT_BUILD_VOLUME = "DOES_NOT_FIT_BUILD_VOLUME"
    SLICING_FAILED = "SLICING_FAILED"
    QUOTE_NOT_FOUND = "QUOTE_NOT_FOUND"
    QUOTE_EXPIRED = "QUOTE_EXPIRED"
    QUOTE_SUPERSEDED = "QUOTE_SUPERSEDED"
    ORDER_NOT_FOUND = "ORDER_NOT_FOUND"
    INVALID_STATE_TRANSITION = "INVALID_STATE_TRANSITION"
    PAYMENT_VERIFICATION_FAILED = "PAYMENT_VERIFICATION_FAILED"
    IDEMPOTENCY_KEY_REUSED = "IDEMPOTENCY_KEY_REUSED"
    RATE_LIMITED = "RATE_LIMITED"
    QUOTA_EXCEEDED = "QUOTA_EXCEEDED"
    INTERNAL_ERROR = "INTERNAL_ERROR"


class Grams(RootModel[StrictFloat]):
    root: Annotated[StrictFloat, Field(ge=0.0, le=1.7976931348623157e308)]


class MaterialId(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            pattern="^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
        ),
    ]


class Millimeters(RootModel[StrictFloat]):
    root: Annotated[StrictFloat, Field(ge=-1.7976931348623157e308, le=1.7976931348623157e308)]


class ModelId(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            pattern="^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
        ),
    ]


class ModelVersionId(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            pattern="^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
        ),
    ]


class Money(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    amountMinor: Annotated[StrictStr, Field(pattern="^(0|-?[1-9][0-9]*)$")]
    currency: CurrencyCode
    exponent: Annotated[StrictInt, Field(ge=0, le=4)]


class OrderId(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            pattern="^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
        ),
    ]


class OrganizationId(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            pattern="^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
        ),
    ]


class PrintJobId(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            pattern="^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
        ),
    ]


class PrinterProfileVersionId(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            pattern="^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
        ),
    ]


class ProjectId(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            pattern="^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
        ),
    ]


class QuoteId(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            pattern="^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
        ),
    ]


class RedactedFieldName(StrEnum):
    authorization = "authorization"
    cookie = "cookie"
    downloadUrl = "downloadUrl"
    fileName = "fileName"
    filename = "filename"
    originalFilename = "originalFilename"
    password = "password"
    paymentPayload = "paymentPayload"
    presignedUrl = "presignedUrl"
    projectName = "projectName"
    providerPayload = "providerPayload"
    secret = "secret"
    signedUrl = "signedUrl"
    token = "token"
    uploadUrl = "uploadUrl"
    url = "url"
    webhookSecret = "webhookSecret"


class Seconds(RootModel[StrictFloat]):
    root: Annotated[StrictFloat, Field(ge=0.0, le=1.7976931348623157e308)]


class SliceJobId(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            pattern="^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
        ),
    ]


class SquareMillimeters(RootModel[StrictFloat]):
    root: Annotated[StrictFloat, Field(ge=0.0, le=1.7976931348623157e308)]


class UserId(RootModel[StrictStr]):
    root: Annotated[
        StrictStr,
        Field(
            pattern="^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}$"
        ),
    ]
