-- sql/00-app-role.sql's `ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ...
-- ON TABLES TO metrika_app` applies to every table the owner role (metrika)
-- creates afterwards, with no way to exclude one table from SQL at the point
-- that statement runs. Prisma's own `_prisma_migrations` tracking table is
-- created by that same owner role, before any migration file executes, so it
-- inherited SELECT/INSERT/UPDATE/DELETE for metrika_app exactly like a real
-- domain table would. That means the application role — the one an
-- accepted-quote-reconstruction bug or a compromised API process would be
-- running as — could rewrite its own migration history, undermining the
-- reproducibility guarantee this whole schema exists to protect.
--
-- This cannot be fixed in sql/00-app-role.sql itself: that file runs at
-- container init, via docker-entrypoint-initdb.d, strictly before
-- `prisma migrate deploy` ever runs, so `_prisma_migrations` does not exist
-- yet when it executes — a REVOKE there would fail with
-- "relation \"_prisma_migrations\" does not exist". So it has to run as a
-- migration.
--
-- The TABLE is not guaranteed to exist here either, and an earlier version of
-- this file asserted that it was: "by the time the migrate engine applies ANY
-- migration.sql (including the very first one), it has already created
-- `_prisma_migrations` for its own bookkeeping". That is true of
-- `migrate deploy`, which applies migrations to the real target database, and
-- FALSE of `migrate dev`, which first replays the whole committed history into
-- a throwaway SHADOW database to compute drift. The shadow database has no
-- `_prisma_migrations` at replay time — Prisma tracks its bookkeeping in the
-- target, not in the shadow — so this statement raised 42P01 there and every
-- `pnpm db:migrate` in the repository failed with P3006/P3018, blocking the
-- authoring of any NEW migration. MEASURED on Prisma 7.9.1.
--
-- The reason the original guard did not catch it is worth keeping, because it
-- is the general trap: a ROLE is a CLUSTER-wide object and a TABLE is a
-- DATABASE-scoped one. The shadow database lives on the same server as the
-- target, so `pg_roles` says `metrika_app` exists there — TRUE, correctly —
-- and the EXECUTE fired against a database that had no such table. The guard
-- tested cluster state to protect a database-scoped statement. MEASURED: in a
-- freshly created, empty database on this same server, the `pg_roles` branch
-- is true and `to_regclass` is NULL.
--
-- Hence BOTH predicates below. `to_regclass` and not `::regclass`: the cast
-- RAISES 42P01 on a missing relation, which would reintroduce the same
-- failure inside the guard meant to prevent it, whereas `to_regclass` returns
-- NULL. It is spelled unqualified, exactly as the REVOKE spells it, so both
-- resolve through the same `search_path` and the guard is testing precisely
-- the object the statement will touch.
--
-- Skipping the REVOKE in the shadow database is correct and not merely
-- tolerable: the shadow exists only so Migrate can diff the resulting SCHEMA,
-- it is dropped immediately afterwards, and a grant is not part of that diff.
-- Drift detection is unaffected.
--
-- The role is NOT guaranteed to exist, though, and this statement is not
-- allowed to assume it does. `REVOKE ... FROM metrika_app` against a role
-- that has never been created raises 42704 "role \"metrika_app\" does not
-- exist" — fatal under `migrate deploy`, and the retry is worse: Prisma
-- records this migration as failed/unfinished in `_prisma_migrations`, so
-- every subsequent `migrate deploy` refuses with P3009 until someone runs
-- `prisma migrate resolve` by hand. Both the harness and `docker-compose`
-- create the role at initdb before any migration ever runs, so this branch
-- is unreachable through either of this repo's two committed paths today —
-- but a migration is forever, and the first place an unguarded REVOKE would
-- actually fire for real is Plan 0D's Terraform-provisioned production
-- database, where "someone runs migrate resolve by hand" means a human
-- doing manual recovery against production during a deploy.
--
-- Guarding it means a database where metrika_app is created AFTER this
-- migration already ran keeps the grants this statement exists to remove —
-- a silent no-op, not a loud one. That is judged acceptable, not just
-- convenient: `ALTER DEFAULT PRIVILEGES ... GRANT ... TO metrika_app` (the
-- statement in sql/00-app-role.sql that creates the hole this migration
-- closes) is itself local/test-only — 00-app-role.sql's own header says it
-- "is never applied there [production]". A role created later in production
-- was never a target of that default-privileges rule in the first place, so
-- it never inherits the grants this REVOKE removes, and there is nothing
-- for the no-op to be silently failing to fix. Do not "tighten" this back to
-- an unconditional REVOKE without re-deriving that production invariant.
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'metrika_app')
     AND to_regclass('"_prisma_migrations"') IS NOT NULL THEN
    EXECUTE 'REVOKE ALL PRIVILEGES ON TABLE "_prisma_migrations" FROM metrika_app';
  END IF;
END $$;
